name: Publish Website to CPanel
on:
  push:
    branches:
      - XXX######
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        ftp-server: XXX##########
        ftp-username: XXX######
        ftp-password: XXX####
